# Generated by Django 5.1.6 on 2025-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_custom_service_client_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contacted_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
